var tip_list = new Array();
tip_list[0]= "Use CSS to easily customize your HTML webpages.";
tip_list[1]="If you don't understand something being taught, ask for help!";
tip_list[2]="To make a comment in Javascript and Java, use //.";
tip_list[3]="To make a comment in Python, use #.";
tip_list[4]="Coding every day will help you understand the concepts better.";
tip_list[5]="If you get frustrated with a code, it might help to take a break and come back to it later with a fresh mind.";
tip_list[6]="You can copy something by selecting it with your cursor then pressing ctrl+c.";
tip_list[7]="You can paste the copied selection by using ctrl+z.";
tip_list[8]="Ctrl+z undoes what you just did!";
tip_list[9]="Alt+tab can switch between your open windows. Just keep hitting tab.";
tip_list[10]="Alt+F4 will close the current window.";
tip_list[11]="Ctrl+f can help you search the current document for specific phrases.";
tip_list[12]="You can learn how to type faster using sites like typing.com and nitrotype.com that help you practice.";
tip_list[13]="To take clearer pictures, make sure you have the object in focus. Try using an actual camera instead of a smartphone!";
tip_list[14]="You can remove the top of a strawberry using a straw!";
tip_list[15]="If you go to www.vogue.co.uk/ and put in the Konami code, a dinosaur shows up!";
tip_list[16]="You can switch out ink cartridges in pens if they're the same brand. Put a blue/black one in a red/equally less desirable color because no one will take them.";
tip_list[17]="Use rubber bands or hair ties to secure wires! No mess, no problem.";
tip_list[18]="The snipping tool on Windows makes for easy screenshots.";
tip_list[19]="You can skip the mess when eating a cupcake by tearing the muffin part in half and putting it on the top. Muffin/frosting sandwich!";
tip_list[20]="Freeze coffee in ice cube trays to stop your coffee from being watered down.";
tip_list[21]="Closed a tab you didn't want to? Use ctrl+shift+t.";
tip_list[22]="Use ctrl+s to easily save your work!";
tip_list[23]="If your computer's running slow, open the task manager using ctrl+shift+esc and see what processes are running.";
tip_list[24]="Want to paste something unformatted? Use ctrl+shift+v instead of ctrl+v.";
tip_list[25]="Delete an entire word with ctrl+backspace.";
tip_list[26]="Make subscript with ctrl+=.";
tip_list[27]="Make superscript with ctrl+shift+=.";
tip_list[28]="Windows key + D will minimize everything!";
tip_list[29]="Use arrays when you're working with multiples of the same things in a code.";
tip_list[30]="Ctrl+w will close the current tab!";

var today_date = new Date();
document.getElementById("p").innerHTML = tip_list[today_date.getDate() - 1];